### ISSUE TITLE
Super high ping when changing to 1.8+

### ISSUE THREAD

**Issue by PiotrekUnityDeveloper** [FlorianMichael/ViaForge#18]
I literally can't move on servers when i change my viaversion to greater than 1.8 cuz the lag is too big. It only occurs on 1.8.9 (till 1.17.1) version of the mod. 1.12.2 works fine

**Comment by MIOGMIOG** [comment]
> I literally can't move on servers when i change my viaversion to greater than 1.8 cuz the lag is too big. It only occurs on 1.8.9 (till 1.17.1) version of the mod. 1.12.2 works fine

1.8.9 has older version of viaversion, you can compile 1.8.9 version from github

**Comment by PiotrekUnityDeveloper** [comment]
okay bro, how do i compile it

**Comment by MIOGMIOG** [comment]
> okay bro, how do i compile it

Its easy, but viaforge doesnt have latest version of viaaversion - look at this pull requests - [here](https://github.com/FlorianMichael/ViaForge/issues/14#issuecomment-1008348006)

**Comment by PiotrekUnityDeveloper** [comment]
IDK how ¯\_(ツ)_/¯

**Comment by MIOGMIOG** [comment]
> IDK how ¯_(ツ)_/¯

just download this file [here](https://github.com/MIOGMIOG/ViaForge/actions/runs/1866281372) (for 1.12.2)

**Comment by PiotrekUnityDeveloper** [comment]
thanks bro

**Comment by MIOGMIOG** [comment]
You can now download version with 1.18.2 support -> 1.8.9 [here](https://github.com/MIOGMIOG/ViaForge/actions/runs/1934689185) and 1.12.2 [here](https://github.com/MIOGMIOG/ViaForge/actions/runs/1934687658)

**Comment by PiotrekUnityDeveloper** [comment]
sounds good 👍 thanks Florian, really cool

**Comment by MIOGMIOG** [comment]
ViaBackwards released [this](https://github.com/ViaVersion/ViaBackwards/commit/539c4e696a6fbe1084ab254e3f0e7241f1b62299) fix, i updated my fork again -> [1.8.9](https://github.com/MIOGMIOG/ViaForge/actions/runs/1946862359), [1.12.2](https://github.com/MIOGMIOG/ViaForge/actions/runs/1946861231)

**Comment by PiotrekUnityDeveloper** [comment]
👀 juicy

**Comment by FlorianMichael** [comment]
so we can close this issue?

**Comment by PiotrekUnityDeveloper** [comment]
sure, why not. thx again bro
