### ISSUE TITLE
Support 1.18

### ISSUE THREAD

**Issue by dianwangwin** [FlorianMichael/ViaForge#19]

**Comment by FlorianMichael** [comment]
As soon as I have time

**Comment by allure-jpg** [comment]
That would be epic

**Comment by xKeksbyte** [comment]
you could port it yourself bruh it needs 3min of work

**Comment by MIOGMIOG** [comment]
> you could port it yourself bruh it needs 3min of work

True, and i created this pull requests: [for 1.8.9](https://github.com/FlorianMichael/ViaForge/pull/22) and [for 1.12.2](https://github.com/FlorianMichael/ViaForge/pull/21).

**Comment by MIOGMIOG** [comment]
![obrazek](https://user-images.githubusercontent.com/82799665/147476497-29e32d6b-646c-405e-807c-e5c1ecb467d0.png)

**Comment by FlorianMichael** [comment]
thank you, I have merged your code

**Comment by MIOGMIOG** [comment]
I forgot 1.18 support for recode-118 branch, so [here](https://github.com/FlorianMichael/ViaForge/pull/28) it is
