### ISSUE TITLE
Compatibility with CubicChunks

### ISSUE THREAD

**Issue by Lolothepro** [FlorianMichael/ViaForge#23]
I wonder, could you add a compatibility with CubicChunk, because for the moment, it does not start with ViaVersion
[latest.log](https://github.com/FlorianMichael/ViaForge/files/7789284/latest.log)

moreover, it would be even better to put the height of the new versions on the old ones with CubicChunk

**Comment by FlorianMichael** [comment]
I'll not implement support for it
