### ISSUE TITLE
This shit doesnt work with other mods for mixin version

### ISSUE THREAD

**Issue by pvpb0t** [FlorianMichael/ViaForge#24]

**Comment by fuckcuff** [comment]
same issue here

**Comment by pvpb0t** [comment]
Cant yall downgrade the mixin version or make it compatible with other mods

**Comment by pvpb0t** [comment]
Also why did you close it, its not resolved!

**Comment by DavidCraftDev** [comment]
I don't know if it's the reason, but I can imagine it was your choice of words. Try to be more friendly next time.

**Comment by pvpb0t** [comment]
> 

How about now?

**Comment by myirlnameisnotsam** [comment]
Same issue and I'm sure that's the problem

**Comment by FlorianMichael** [comment]
I have now changed the mixin version and uploaded the patch to Curseforge

https://www.curseforge.com/minecraft/mc-mods/viaforge/files/3595536
