### ISSUE TITLE
Add 1.7 Protocols

### ISSUE THREAD

**Issue by FlorianMichael** [FlorianMichael/ViaForge#3]

**Comment by terminated-star** [comment]
Hey, I would love a 1.7.10 version of this mod, but I saw this was labeled "wontfix". Does this mean newer versions won't be able to use the 1.7 protocols, or 1.7 wont be able to use newer protocols (or both)? Thanks.

**Comment by FlorianMichael** [comment]
There will never be a native mod for the 1.7, maybe there will be a protocol for the 1.7 at some point.

**Comment by MIOGMIOG** [comment]
> There will never be a native mod for the 1.7, maybe there will be a protocol for the 1.7 at some point.

You can use [DirtMultiversion](https://github.com/DirtPowered/DirtMultiversion) to support the 1.7 protocol in newer versions.

**Comment by MIOGMIOG** [comment]
https://github.com/MIOGMIOG/ViaForge/projects/2 Solves this issue
