### ISSUE TITLE
Not working with Liteloader on 1.8.9

### ISSUE THREAD

**Issue by HowardZHY** [FlorianMichael/ViaForge#36]
Unsupported mixin class version 52. Mixin requires compatibility level JAVA_8 or above.
[fml-client-latest.log](https://github.com/FlorianMichael/ViaForge/files/8243151/fml-client-latest.log)

**Comment by FlorianMichael** [comment]
This Mod isn't for Liteloader

**Comment by FlorianMichael** [comment]
ok
