### ISSUE TITLE
My suggestions for this mod

### ISSUE THREAD

**Issue by MIOGMIOG** [FlorianMichael/ViaForge#37]
These features will be good to add:
*1. Textures and models for blocks, items, armors and entities (likely patching ViaVersion will be required)
*2. Add compatability for CubicChunks - support higher build limits for 1.18+ and classic servers (probably requires patching viaversion)
3. Per-server version setting; For each server, ability to set different versions (so we dont have to switch global version setting)
4. For version list, add "automatic" option - it will ping server and get supported versions and it will use closest supported server version (it already is in ViaFabric)
5. Implement ViaLegacy
*6. Qol features for ViaLegacy (remove hunger bar when version is beta 1.7-, etc... Like in this project: [ViaLegacy for Multiconnect](https://github.com/Gaming32/vialegacy-multiconnect/tree/main/src/main/java/io/github/gaming32/vialegacymulticonnect/protocols))

For this to work with other mods, ViaForge will have to split to 2 jars - ViaForge core (current project plus features here without star) and ViaForge QOL (will require ViaForge core installed in mods folder with it and it will add features with stars)

**Comment by HowardZHY** [comment]
Project 1 is like the labymod plugin one
Project 3 is "easy" with Optifine
Project 4 would be *really* hard

**Comment by MIOGMIOG** [comment]
> Project 1 is like the labymod plugin one Project 3 is "easy" with Optifine Project 4 would be _really_ hard

ok but it would have to be an optifine mod REQUIRED DEPENDENCY which we don't want, just add new items and change viaversion mappings (I don't think you can put nbt tags / something like that in viaversion mappings)

**Comment by MIOGMIOG** [comment]
> First problem, DirtMultiversion does not have Maven repository [issue 19](https://github.com/DirtPowered/DirtMultiversion/issues/19)

Resolved, https://jitpack.io/#DirtPowered/DirtMultiversion/master-SNAPSHOT

**Comment by HowardZHY** [comment]
> > Project 1 is like the labymod plugin one Project 3 is "easy" with Optifine Project 4 would be _really_ hard
> 
> ok but it would have to be an optifine mod REQUIRED DEPENDENCY which we don't want, just add new items and change viaversion mappings (I don't think you can put nbt tags / something like that in viaversion mappings)

using names like 1.16 xx is just enough, and VB has an NBT tag for items. I don't really know will placed blocks work or not

**Comment by MIOGMIOG** [comment]
> These features will be good to add: *1. Textures and models for blocks, items, armors and entities (likely patching ViaVersion will be required) *2. Add compatability for CubicChunks - support higher build limits for 1.18+ and classic servers (probably requires patching viaversion) 3. Per-server version setting; For each server, ability to set different versions (so we dont have to switch global version setting) 4. For version list, add "automatic" option - it will ping server and get supported versions and it will use closest supported server version (it already is in ViaFabric) 5. Implement ViaLegacy *6. Qol features for ViaLegacy (remove hunger bar when version is beta 1.7-, etc... Like in this project: [ViaLegacy for Multiconnect](https://github.com/Gaming32/vialegacy-multiconnect/tree/main/src/main/java/io/github/gaming32/vialegacymulticonnect/protocols))
> 
> For this to work with other mods, ViaForge will have to split to 2 jars - ViaForge core (current project plus features here without star) and ViaForge QOL (will require ViaForge core installed in mods folder with it and it will add features with stars)

Splitting to 2 jars will be good, because for example entity models for new entities or removing hunger bar can break other mods

**Comment by MIOGMIOG** [comment]
This should move to ViaForgePlus repo
