### ISSUE TITLE
1.8.9 Player moving glitch

### ISSUE THREAD

**Issue by HowardZHY** [FlorianMichael/ViaForge#48]
The bug we've talked about on Discord, still when 1.8.9 join 1.19 server.

**Comment by HowardZHY** [comment]
@FlorianMichael u probably forget to merge the patch to github

**Comment by FlorianMichael** [comment]
will be fixed sometimes

**Comment by fwsrr** [comment]
@HowardZHY did u get it to fix or still not?

**Comment by HowardZHY** [comment]
> @HowardZHY did u get it to fix or still not?

This issue is too outdate, I don;t think it exists anymore except the server has some anticheat

**Comment by fwsrr** [comment]
No the bug is still there, when joining a server I sometimes get stuck on a block and just can't move or look any other way then the front.
