### ISSUE TITLE
cant connect to 2b2troll with 1.12.2

### ISSUE THREAD

**Issue by arceuss** [FlorianMichael/ViaForge#5]
![image](https://user-images.githubusercontent.com/28229451/110252439-ac498300-7f42-11eb-81ce-1181663ecfed.png)
tried both future and vanilla with forge and both didnt work

**Comment by FlorianMichael** [comment]
What mods do you use other than ViaForge?

**Comment by arceuss** [comment]
i didnt use any other ones when testing vanilla

**Comment by FlorianMichael** [comment]
Did you use other mods when testing ViaForge?

**Comment by arceuss** [comment]
![image](https://user-images.githubusercontent.com/28229451/110261318-f8112200-7f6c-11eb-8293-f02bc0b18d84.png)
this is all i was using with my other test to see if it was only my hack client

**Comment by arceuss** [comment]
the ip is 2b2troll.org on 1.16.5 if you wanna try it

**Comment by FlorianMichael** [comment]
Can you try it with ViaFabric?

**Comment by arceuss** [comment]
> 
> 
> Can you try it with ViaFabric?

what version

**Comment by FlorianMichael** [comment]
1.16

**Comment by RaphiMC** [comment]
The provided server ip doesn't work for me (on 1.16.5)

**Comment by FlorianMichael** [comment]
Then it's probably a server error, it doesn't work for me either.
