### ISSUE TITLE
Stuck on "Loading Terrain" endcrystal.me

### ISSUE THREAD

**Issue by MOMIN5** [FlorianMichael/ViaForge#6]
I have tried and it works on test.2b2t.org(which doesnt has a proxy), however on ecme it is stuck on loading terrian, ecme uses a proxy which makes the player then connect to the main server
![Capture](https://user-images.githubusercontent.com/70264419/111869277-9907d000-89a4-11eb-888e-fb027ab039d0.PNG)

As you can see i am connected to the server, on the multimc console it shows that im connecting and its displaying all the messages of the server, its similiar to #5 as 2b2troll also used a proxy(The owner closed the server now). 

Also im pretty sure it worked on "till 21w45a version"(of viaforge) and it started giving this bug on the lastest version

**Comment by MOMIN5** [comment]
I have also tried it without any clients, it still gives the same result. 

Can you give me the 21w45a version until this is fixed, i cant seem to find it anywhere

**Comment by FlorianMichael** [comment]
I just think it's a ViaVersion bug, between the ViaForge versions only the ViaVersion version is different, I haven't changed anything else. Maybe you can report this at ViaVersion

**Comment by MOMIN5** [comment]
ok, is there a way i can get the old 21w45a version? i lost it and cant find a download, and the curseforge only has the new version
