### ISSUE TITLE
1.12.2 to 1.18.2 bugged chests

### ISSUE THREAD

**Issue by NewProGamer122** [FlorianMichael/ViaForge#61]
When you are on 1.12.2 and join a later version, if there are double chests next to each other they will be invis

**Comment by FlorianMichael** [comment]
This is a ViaVersion issue

**Comment by NewProGamer122** [comment]
Im only using viaforge, unless it does not matter

**Comment by FlorianMichael** [comment]
ViaForge is ViaVersion for Forge, so you are using ViaVersion, I won't fix this since ViaForge is dead

**Comment by NewProGamer122** [comment]
ah ok then
